
const SET_SINGER = 'SET_SINGER';

const SET_PLAYING_STATE = 'SET_PLAYING_STATE';

const SET_FULL_SCREEN = 'SET_FULL_SCREEN';

const SET_PLAYLIST = 'SET_PLAYLIST';

const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST';

const SET_PLAY_MODE = 'SET_PLAY_MODE';

const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';

const SET_DISC = 'SET_DISC';

const SET_TOP_LIST = 'SET_TOP_LIST';

const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY';

export {
  SET_SINGER,
  SET_PLAYING_STATE,
  SET_FULL_SCREEN,
  SET_PLAYLIST,
  SET_SEQUENCE_LIST,
  SET_PLAY_MODE,
  SET_CURRENT_INDEX,
  SET_DISC,
  SET_TOP_LIST,
  SET_SEARCH_HISTORY,
  SET_PLAY_HISTORY,
};
